import type { Theme } from "./types.ts";

export const THEMES: Theme[] = [
  {
    name: "terracotta",
    description: "Mediterranean warmth — burnt orange and clay tones on cream",
    bg: "#F5EDE4",
    text: "#8B4513",
    gradientColor: "#F5EDE4",
    water: "#A8C4C4",
    parks: "#E8E0D0",
    roadMotorway: "#A0522D",
    roadPrimary: "#B8653A",
    roadSecondary: "#C9846A",
    roadTertiary: "#D9A08A",
    roadResidential: "#E5C4B0",
    roadDefault: "#D9A08A",
  },
  {
    name: "midnight_blue",
    description: "Deep ocean blues with warm gold roads — Dubai style",
    bg: "#0A1628",
    text: "#D4AF37",
    gradientColor: "#0A1628",
    water: "#061020",
    parks: "#0F2235",
    roadMotorway: "#D4AF37",
    roadPrimary: "#C9A227",
    roadSecondary: "#A8893A",
    roadTertiary: "#8B7355",
    roadResidential: "#6B5B4F",
    roadDefault: "#8B7355",
  },
  {
    name: "noir",
    description: "Dark greys with white roads — high contrast",
    bg: "#000000",
    text: "#FFFFFF",
    gradientColor: "#000000",
    water: "#0A0A0A",
    parks: "#111111",
    roadMotorway: "#FFFFFF",
    roadPrimary: "#D4D4D4",
    roadSecondary: "#A8A8A8",
    roadTertiary: "#808080",
    roadResidential: "#606060",
    roadDefault: "#808080",
  },
  {
    name: "neon_cyberpunk",
    description: "Vibrant neon on dark cyberpunk background",
    bg: "#0D0D1A",
    text: "#00FFFF",
    gradientColor: "#0D0D1A",
    water: "#0A0A15",
    parks: "#151525",
    roadMotorway: "#FF00FF",
    roadPrimary: "#00FFFF",
    roadSecondary: "#00C8C8",
    roadTertiary: "#0098A0",
    roadResidential: "#006870",
    roadDefault: "#0098A0",
  },
  {
    name: "japanese_ink",
    description: "Sumi-e inspired — warm ivory, warm gray roads, single red accent",
    bg: "#FAF8F5",
    text: "#2C2C2C",
    gradientColor: "#FAF8F5",
    water: "#E8E4E0",
    parks: "#F0EDE8",
    roadMotorway: "#8B2500",
    roadPrimary: "#4A4A4A",
    roadSecondary: "#6A6A6A",
    roadTertiary: "#909090",
    roadResidential: "#B8B8B8",
    roadDefault: "#909090",
  },
  {
    name: "emerald",
    description: "Rich greens and teals",
    bg: "#062C22",
    text: "#E3F9F1",
    gradientColor: "#062C22",
    water: "#0D4536",
    parks: "#0F523E",
    roadMotorway: "#4ADEB0",
    roadPrimary: "#2DB88F",
    roadSecondary: "#249673",
    roadTertiary: "#1B7559",
    roadResidential: "#155C46",
    roadDefault: "#155C46",
  },
  {
    name: "sunset",
    description: "Warm evening hues — oranges, pinks, purples",
    bg: "#FDF5F0",
    text: "#C45C3E",
    gradientColor: "#FDF5F0",
    water: "#F0D8D0",
    parks: "#F8E8E0",
    roadMotorway: "#C45C3E",
    roadPrimary: "#D87A5A",
    roadSecondary: "#E8A088",
    roadTertiary: "#F0B8A8",
    roadResidential: "#F5D0C8",
    roadDefault: "#E8A088",
  },
  {
    name: "ocean",
    description: "Cool coastal blues",
    bg: "#F0F8FA",
    text: "#1A5F7A",
    gradientColor: "#F0F8FA",
    water: "#B8D8E8",
    parks: "#D8EAE8",
    roadMotorway: "#1A5F7A",
    roadPrimary: "#2A7A9A",
    roadSecondary: "#4A9AB8",
    roadTertiary: "#70B8D0",
    roadResidential: "#A0D0E0",
    roadDefault: "#4A9AB8",
  },
  {
    name: "autumn",
    description: "Warm fall colors — oranges, browns, golds",
    bg: "#FBF7F0",
    text: "#8B4513",
    gradientColor: "#FBF7F0",
    water: "#D8CFC0",
    parks: "#E8E0D0",
    roadMotorway: "#8B2500",
    roadPrimary: "#B8450A",
    roadSecondary: "#CC7A30",
    roadTertiary: "#D9A050",
    roadResidential: "#E8C888",
    roadDefault: "#CC7A30",
  },
  {
    name: "forest",
    description: "Deep greens and earthy browns",
    bg: "#F0F4F0",
    text: "#2D4A3E",
    gradientColor: "#F0F4F0",
    water: "#B8D4D4",
    parks: "#D4E8D4",
    roadMotorway: "#2D4A3E",
    roadPrimary: "#3D6B55",
    roadSecondary: "#5A8A70",
    roadTertiary: "#7AAA90",
    roadResidential: "#A0C8B0",
    roadDefault: "#7AAA90",
  },
  {
    name: "blueprint",
    description: "Classic blueprint style — blue background, white lines",
    bg: "#1A3A5C",
    text: "#E8F4FF",
    gradientColor: "#1A3A5C",
    water: "#0F2840",
    parks: "#1E4570",
    roadMotorway: "#E8F4FF",
    roadPrimary: "#C5DCF0",
    roadSecondary: "#9FC5E8",
    roadTertiary: "#7BAED4",
    roadResidential: "#5A96C0",
    roadDefault: "#7BAED4",
  },
  {
    name: "copper_patina",
    description: "Oxidized copper tones — teals and warm browns",
    bg: "#E8F0F0",
    text: "#2A5A5A",
    gradientColor: "#E8F0F0",
    water: "#C0D8D8",
    parks: "#D8E8E0",
    roadMotorway: "#B87333",
    roadPrimary: "#5A8A8A",
    roadSecondary: "#6B9E9E",
    roadTertiary: "#88B4B4",
    roadResidential: "#A8CCCC",
    roadDefault: "#88B4B4",
  },
  {
    name: "warm_beige",
    description: "Clean minimal beige tones",
    bg: "#F5F0E8",
    text: "#6B5B4F",
    gradientColor: "#F5F0E8",
    water: "#DDD5C8",
    parks: "#E8E4D8",
    roadMotorway: "#8B7355",
    roadPrimary: "#A08B70",
    roadSecondary: "#B5A48E",
    roadTertiary: "#C9BBAA",
    roadResidential: "#D9CFC2",
    roadDefault: "#C9BBAA",
  },
  {
    name: "monochrome_blue",
    description: "Single blue hue with varying lightness",
    bg: "#F5F8FA",
    text: "#1A3A5F",
    gradientColor: "#F5F8FA",
    water: "#D0E0F0",
    parks: "#E0EAF2",
    roadMotorway: "#1A3A5C",
    roadPrimary: "#2A5580",
    roadSecondary: "#4A7AA8",
    roadTertiary: "#7AA0C8",
    roadResidential: "#A8C4E0",
    roadDefault: "#4A7AA8",
  },
  {
    name: "pastel_dream",
    description: "Soft pastel colors — gentle and light",
    bg: "#FAF7F2",
    text: "#5D5A6D",
    gradientColor: "#FAF7F2",
    water: "#D4E4ED",
    parks: "#E8EDE4",
    roadMotorway: "#7B8794",
    roadPrimary: "#9BA4B0",
    roadSecondary: "#B5AEBB",
    roadTertiary: "#C9C0C9",
    roadResidential: "#D8D2D8",
    roadDefault: "#C9C0C9",
  },
  {
    name: "contrast_zones",
    description: "High contrast with distinct zone colors",
    bg: "#FFFFFF",
    text: "#000000",
    gradientColor: "#FFFFFF",
    water: "#B0B0B0",
    parks: "#ECECEC",
    roadMotorway: "#000000",
    roadPrimary: "#0F0F0F",
    roadSecondary: "#252525",
    roadTertiary: "#404040",
    roadResidential: "#5A5A5A",
    roadDefault: "#404040",
  },
  {
    name: "gradient_roads",
    description: "Roads colored by a warm gradient, clean background",
    bg: "#FFFFFF",
    text: "#000000",
    gradientColor: "#FFFFFF",
    water: "#D5D5D5",
    parks: "#EFEFEF",
    roadMotorway: "#050505",
    roadPrimary: "#151515",
    roadSecondary: "#2A2A2A",
    roadTertiary: "#404040",
    roadResidential: "#555555",
    roadDefault: "#404040",
  },
];

export function getTheme(name: string): Theme | undefined {
  return THEMES.find((t) => t.name === name);
}

export function listThemes(): string[] {
  return THEMES.map((t) => t.name);
}
